In [1]:
import pandas as pd
import numpy as np
import requests
import os
from dotenv import load_dotenv, find_dotenv
from datetime import date, timedelta

In [2]:
url = os.getenv("STOCK_ENDPOINT")
api_key = os.getenv("ALPHAVANTAGE_API_KEY")
stock = os.getenv("STOCK_NAME")

In [3]:


params = {
    'function': 'TIME_SERIES_DAILY',
    'symbol': stock,
    'apikey': api_key
}
r = requests.get(url, params=params)
data = r.json()

print(data)

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'TSLA', '3. Last Refreshed': '2026-10-09', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2026-10-09': {'1. open': '382.3800', '2. high': '388.5600', '3. low': '379.7100', '4. close': '382.7000', '5. volume': '38783646'}, '2026-10-08': {'1. open': '374.1200', '2. high': '375.9600', '3. low': '368.0301', '4. close': '375.0000', '5. volume': '28394945'}, '2026-10-07': {'1. open': '378.4450', '2. high': '382.3499', '3. low': '374.4300', '4. close': '377.8100', '5. volume': '25594563'}, '2026-10-06': {'1. open': '381.9750', '2. high': '383.3300', '3. low': '378.5200', '4. close': '380.6800', '5. volume': '27735438'}, '2026-10-05': {'1. open': '369.0000', '2. high': '381.5900', '3. low': '364.9100', '4. close': '378.7300', '5. volume': '42232669'}, '2026-10-02': {'1. open': '360.0800', '2. high': '374.6000', '3. low': '359.4110', '4. close': '370.5900', '5. volume': '55330140'}, '2026-10-01': {'1. open': '356.8100', '2. high': '359.7900', '3. low': '353.8000', '4. close': '354.1100', '5. volume': '31080774'}, '2026-09-30': {'1. open': '352.1100', '2. high': '355.2190', '3. low': '345.8800', '4. close': '354.8100', '5. volume': '39235838'}, '2026-09-29': {'1. open': '358.4000', '2. high': '358.7400', '3. low': '351.6700', '4. close': '352.8400', '5. volume': '32492406'}, '2026-09-28': {'1. open': '368.0600', '2. high': '369.4300', '3. low': '356.8000', '4. close': '357.4500', '5. volume': '39452901'}, '2026-09-25': {'1. open': '384.6200', '2. high': '386.8300', '3. low': '367.6700', '4. close': '372.1100', '5. volume': '45999470'}, '2026-09-24': {'1. open': '377.3500', '2. high': '383.3324', '3. low': '375.7000', '4. close': '377.9400', '5. volume': '26165727'}, '2026-09-23': {'1. open': '380.1000', '2. high': '386.7000', '3. low': '377.5750', '4. close': '380.1200', '5. volume': '33522492'}, '2026-09-22': {'1. open': '379.0690', '2. high': '380.4200', '3. low': '372.8800', '4. close': '378.9000', '5. volume': '28229908'}, '2026-09-21': {'1. open': '371.6350', '2. high': '378.3600', '3. low': '371.0700', '4. close': '375.3000', '5. volume': '36599609'}, '2026-09-18': {'1. open': '369.0000', '2. high': '370.9000', '3. low': '360.7510', '4. close': '364.2700', '5. volume': '51922256'}, '2026-09-17': {'1. open': '367.4800', '2. high': '374.1200', '3. low': '363.2200', '4. close': '366.2000', '5. volume': '38924057'}, '2026-09-16': {'1. open': '357.9250', '2. high': '365.1000', '3. low': '354.8913', '4. close': '358.0800', '5. volume': '32177388'}, '2026-09-15': {'1. open': '358.7500', '2. high': '362.3900', '3. low': '354.0500', '4. close': '356.5800', '5. volume': '30317727'}, '2026-09-14': {'1. open': '359.7800', '2. high': '367.7300', '3. low': '357.0400', '4. close': '358.9700', '5. volume': '32477181'}, '2026-09-11': {'1. open': '364.2000', '2. high': '368.6600', '3. low': '361.6000', '4. close': '365.4400', '5. volume': '30153019'}, '2026-09-10': {'1. open': '360.5950', '2. high': '369.2100', '3. low': '357.6800', '4. close': '363.5600', '5. volume': '29667241'}, '2026-09-09': {'1. open': '368.2500', '2. high': '375.4400', '3. low': '366.0000', '4. close': '367.8100', '5. volume': '32564336'}, '2026-09-08': {'1. open': '357.0950', '2. high': '370.0000', '3. low': '355.7500', '4. close': '368.1600', '5. volume': '51078786'}, '2026-09-04': {'1. open': '362.0700', '2. high': '364.6900', '3. low': '351.3201', '4. close': '354.0800', '5. volume': '65018209'}, '2026-09-03': {'1. open': '365.8200', '2. high': '384.0400', '3. low': '365.8200', '4. close': '376.3650', '5. volume': '63600987'}, '2026-09-02': {'1. open': '360.4100', '2. high': '360.6200', '3. low': '349.9200', '4. close': '357.0100', '5. volume': '33951909'}, '2026-09-01': {'1. open': '360.9000', '2. high': '362.7000', '3. low': '352.9600', '4. close': '356.0900', '5. volume': '36193926'}, '2026-08-31': {'1. open': '347.2100', '2. high': '368.9200', '3. low': '347.1500', '4. close': '367.9500', '5. volume': '61732258'}, '2026-08-28': {'1. open': '357.0950', '2. high': '358.8000', '3. low': '345.2000', '4. close': '348.7500', '5. volume': '32972214'}, '2026-08-27': {'1. open': '346.1550', '2. high': '355.7400', '3. low': '345.4500', '4. close': '354.8100', '5. volume': '30136164'}, '2026-08-26': {'1. open': '345.2700', '2. high': '351.9300', '3. low': '342.5300', '4. close': '345.8200', '5. volume': '28573007'}, '2026-08-25': {'1. open': '349.5800', '2. high': '357.0000', '3. low': '349.2003', '4. close': '350.2500', '5. volume': '29816685'}, '2026-08-24': {'1. open': '361.4100', '2. high': '363.2400', '3. low': '348.2600', '4. close': '348.9500', '5. volume': '39190484'}, '2026-08-21': {'1. open': '349.8800', '2. high': '366.5000', '3. low': '346.9000', '4. close': '362.8600', '5. volume': '59223958'}, '2026-08-20': {'1. open': '346.2000', '2. high': '347.5000', '3. low': '338.9600', '4. close': '345.1300', '5. volume': '30766360'}, '2026-08-19': {'1. open': '338.8900', '2. high': '351.6200', '3. low': '335.7000', '4. close': '351.1200', '5. volume': '36735428'}, '2026-08-18': {'1. open': '333.2200', '2. high': '340.5300', '3. low': '331.1200', '4. close': '336.8700', '5. volume': '27994466'}, '2026-08-17': {'1. open': '340.6900', '2. high': '345.4500', '3. low': '337.4800', '4. close': '339.3000', '5. volume': '26037093'}, '2026-08-14': {'1. open': '342.3300', '2. high': '351.2600', '3. low': '335.3306', '4. close': '342.2700', '5. volume': '45437144'}, '2026-08-13': {'1. open': '327.2000', '2. high': '341.6400', '3. low': '325.2400', '4. close': '339.9600', '5. volume': '34708303'}, '2026-08-12': {'1. open': '335.0000', '2. high': '335.5000', '3. low': '323.6400', '4. close': '327.5100', '5. volume': '28698879'}, '2026-08-11': {'1. open': '332.8000', '2. high': '336.2000', '3. low': '329.5300', '4. close': '332.8100', '5. volume': '23345233'}, '2026-08-10': {'1. open': '326.5950', '2. high': '332.0500', '3. low': '326.1500', '4. close': '330.8800', '5. volume': '25003808'}, '2026-08-07': {'1. open': '322.3400', '2. high': '333.7300', '3. low': '321.2508', '4. close': '328.5800', '5. volume': '39492345'}, '2026-08-06': {'1. open': '317.0500', '2. high': '323.0000', '3. low': '315.5205', '4. close': '319.5300', '5. volume': '26033776'}, '2026-08-05': {'1. open': '323.4200', '2. high': '327.1400', '3. low': '320.2800', '4. close': '321.5500', '5. volume': '27820813'}, '2026-08-04': {'1. open': '324.0000', '2. high': '329.5700', '3. low': '320.7901', '4. close': '327.3500', '5. volume': '33318303'}, '2026-08-03': {'1. open': '310.9600', '2. high': '324.6500', '3. low': '310.4250', '4. close': '322.0800', '5. volume': '38281362'}, '2026-07-31': {'1. open': '309.6900', '2. high': '315.5000', '3. low': '301.9700', '4. close': '311.2100', '5. volume': '36630560'}, '2026-07-30': {'1. open': '302.7000', '2. high': '310.8700', '3. low': '301.3300', '4. close': '308.8500', '5. volume': '38005390'}, '2026-07-29': {'1. open': '307.1400', '2. high': '309.0600', '3. low': '297.3800', '4. close': '298.3200', '5. volume': '39478039'}, '2026-07-28': {'1. open': '305.9250', '2. high': '311.1600', '3. low': '300.6900', '4. close': '307.4400', '5. volume': '39802421'}, '2026-07-27': {'1. open': '313.2400', '2. high': '317.0000', '3. low': '304.2800', '4. close': '309.2200', '5. volume': '44919377'}, '2026-07-24': {'1. open': '320.7200', '2. high': '322.9600', '3. low': '306.5100', '4. close': '313.0300', '5. volume': '62760007'}, '2026-07-23': {'1. open': '341.0000', '2. high': '342.1100', '3. low': '315.7350', '4. close': '319.6900', '5. volume': '115606413'}, '2026-07-22': {'1. open': '375.5300', '2. high': '380.1700', '3. low': '372.9000', '4. close': '374.0100', '5. volume': '30646124'}, '2026-07-21': {'1. open': '371.1650', '2. high': '384.0700', '3. low': '369.9800', '4. close': '378.9300', '5. volume': '32735334'}, '2026-07-20': {'1. open': '386.0450', '2. high': '386.6100', '3. low': '369.4250', '4. close': '369.5700', '5. volume': '33901516'}, '2026-07-17': {'1. open': '381.7800', '2. high': '385.6899', '3. low': '377.2200', '4. close': '380.8400', '5. volume': '31394594'}, '2026-07-16': {'1. open': '392.3500', '2. high': '395.3100', '3. low': '385.3200', '4. close': '391.0600', '5. volume': '29269113'}, '2026-07-15': {'1. open': '399.3950', '2. high': '406.5895', '3. low': '390.6600', '4. close': '394.4600', '5. volume': '31549805'}, '2026-07-14': {'1. open': '399.0500', '2. high': '402.2200', '3. low': '394.7600', '4. close': '396.1800', '5. volume': '23384992'}, '2026-07-13': {'1. open': '404.6100', '2. high': '405.5700', '3. low': '391.3700', '4. close': '394.7600', '5. volume': '32809171'}, '2026-07-10': {'1. open': '410.4900', '2. high': '413.1600', '3. low': '402.8101', '4. close': '407.7600', '5. volume': '33409995'}, '2026-07-09': {'1. open': '393.9900', '2. high': '407.8600', '3. low': '390.8631', '4. close': '406.5500', '5. volume': '37834988'}, '2026-07-08': {'1. open': '399.3750', '2. high': '399.6300', '3. low': '390.5100', '4. close': '394.0600', '5. volume': '33844906'}, '2026-07-07': {'1. open': '416.9600', '2. high': '419.5600', '3. low': '401.8800', '4. close': '402.9000', '5. volume': '38149901'}, '2026-07-06': {'1. open': '397.5000', '2. high': '420.0000', '3. low': '390.5000', '4. close': '419.7700', '5. volume': '54727861'}, '2026-07-02': {'1. open': '428.0100', '2. high': '432.3500', '3. low': '389.3011', '4. close': '393.4500', '5. volume': '73915762'}, '2026-07-01': {'1. open': '421.4600', '2. high': '432.8599', '3. low': '418.0901', '4. close': '425.3000', '5. volume': '40127902'}, '2026-06-30': {'1. open': '406.0000', '2. high': '424.5400', '3. low': '406.0000', '4. close': '420.6000', '5. volume': '43385619'}, '2026-06-29': {'1. open': '381.7900', '2. high': '413.2700', '3. low': '379.3000', '4. close': '411.8400', '5. volume': '57645798'}, '2026-06-26': {'1. open': '370.1500', '2. high': '387.8000', '3. low': '368.6000', '4. close': '379.7100', '5. volume': '53434138'}, '2026-06-25': {'1. open': '375.2700', '2. high': '379.1170', '3. low': '371.2210', '4. close': '375.1200', '5. volume': '30259987'}, '2026-06-24': {'1. open': '380.0800', '2. high': '384.5800', '3. low': '373.0500', '4. close': '375.5300', '5. volume': '37081421'}, '2026-06-23': {'1. open': '392.6100', '2. high': '392.8700', '3. low': '379.0600', '4. close': '381.6100', '5. volume': '50420210'}, '2026-06-22': {'1. open': '394.8500', '2. high': '414.7500', '3. low': '394.4000', '4. close': '405.0500', '5. volume': '47819486'}, '2026-06-18': {'1. open': '398.0950', '2. high': '402.5200', '3. low': '384.7000', '4. close': '400.4900', '5. volume': '58384713'}, '2026-06-17': {'1. open': '401.5300', '2. high': '405.9400', '3. low': '393.7600', '4. close': '396.3800', '5. volume': '43534299'}, '2026-06-16': {'1. open': '404.1100', '2. high': '412.4200', '3. low': '400.5400', '4. close': '404.6600', '5. volume': '40255473'}, '2026-06-15': {'1. open': '412.3700', '2. high': '416.0000', '3. low': '407.1000', '4. close': '411.1500', '5. volume': '45620514'}, '2026-06-12': {'1. open': '399.4900', '2. high': '406.6800', '3. low': '386.7600', '4. close': '406.4300', '5. volume': '63652286'}, '2026-06-11': {'1. open': '388.2800', '2. high': '399.5400', '3. low': '380.6600', '4. close': '399.1500', '5. volume': '45324348'}, '2026-06-10': {'1. open': '391.5400', '2. high': '397.0900', '3. low': '380.1500', '4. close': '381.5900', '5. volume': '49695583'}, '2026-06-09': {'1. open': '411.0300', '2. high': '418.5000', '3. low': '384.2400', '4. close': '396.6800', '5. volume': '59940230'}, '2026-06-08': {'1. open': '396.3300', '2. high': '412.9400', '3. low': '394.7200', '4. close': '408.9500', '5. volume': '50328834'}, '2026-06-05': {'1. open': '420.5000', '2. high': '424.6799', '3. low': '388.5900', '4. close': '391.0000', '5. volume': '63420177'}, '2026-06-04': {'1. open': '419.8400', '2. high': '426.3499', '3. low': '417.1600', '4. close': '418.4500', '5. volume': '35323259'}, '2026-06-03': {'1. open': '418.7000', '2. high': '433.6000', '3. low': '416.0000', '4. close': '423.7000', '5. volume': '44500733'}, '2026-06-02': {'1. open': '418.2200', '2. high': '424.4200', '3. low': '413.6500', '4. close': '423.7400', '5. volume': '37596045'}, '2026-06-01': {'1. open': '427.4900', '2. high': '429.6000', '3. low': '415.4300', '4. close': '415.8800', '5. volume': '44937852'}, '2026-05-29': {'1. open': '439.8450', '2. high': '441.0700', '3. low': '428.1400', '4. close': '435.7900', '5. volume': '45176821'}, '2026-05-28': {'1. open': '437.6150', '2. high': '443.9600', '3. low': '436.3000', '4. close': '442.1000', '5. volume': '32434996'}, '2026-05-27': {'1. open': '442.8900', '2. high': '445.6000', '3. low': '435.5200', '4. close': '440.3600', '5. volume': '44656505'}, '2026-05-26': {'1. open': '430.2600', '2. high': '435.2000', '3. low': '426.1200', '4. close': '433.5900', '5. volume': '45658897'}, '2026-05-22': {'1. open': '422.6650', '2. high': '431.5100', '3. low': '420.5100', '4. close': '426.0100', '5. volume': '46104710'}, '2026-05-21': {'1. open': '422.1750', '2. high': '426.9500', '3. low': '412.9000', '4. close': '417.8500', '5. volume': '42636854'}, '2026-05-20': {'1. open': '407.6000', '2. high': '417.4600', '3. low': '406.3900', '4. close': '417.2600', '5. volume': '44484579'}, '2026-05-19': {'1. open': '403.1600', '2. high': '405.6300', '3. low': '393.6300', '4. close': '404.1100', '5. volume': '46500551'}}}

In [4]:
daily_data = data['Time Series (Daily)']

In [5]:

yesterday = (date.today() - timedelta(days=1)).isoformat()
day_before = (date.today() - timedelta(days=2)).isoformat()

yesterday_close = float(daily_data[yesterday]["4. close"])
day_before_close = float(daily_data[day_before]["4. close"])

In [6]:
abs_val_diff = np.abs(yesterday_close - day_before_close)
abs_val_diff

2.8100000000000023

In [7]:
pct_diff = abs_val_diff / (yesterday_close + day_before_close/2) * 100

In [8]:
pct_diff

0.49831088569883264

In [9]:
daily_data[yesterday]

{'1. open': '374.1200',
 '2. high': '375.9600',
 '3. low': '368.0301',
 '4. close': '375.0000',
 '5. volume': '28394945'}

In [10]:
daily_data[day_before]

{'1. open': '378.4450',
 '2. high': '382.3499',
 '3. low': '374.4300',
 '4. close': '377.8100',
 '5. volume': '25594563'}

In [11]:
[print(f"{key}: {value}") for (key, value) in data.items()]

Meta Data: {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'TSLA', '3. Last Refreshed': '2026-10-09', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}
Time Series (Daily): {'2026-10-09': {'1. open': '382.3800', '2. high': '388.5600', '3. low': '379.7100', '4. close': '382.7000', '5. volume': '38783646'}, '2026-10-08': {'1. open': '374.1200', '2. high': '375.9600', '3. low': '368.0301', '4. close': '375.0000', '5. volume': '28394945'}, '2026-10-07': {'1. open': '378.4450', '2. high': '382.3499', '3. low': '374.4300', '4. close': '377.8100', '5. volume': '25594563'}, '2026-10-06': {'1. open': '381.9750', '2. high': '383.3300', '3. low': '378.5200', '4. close': '380.6800', '5. volume': '27735438'}, '2026-10-05': {'1. open': '369.0000', '2. high': '381.5900', '3. low': '364.9100', '4. close': '378.7300', '5. volume': '42232669'}, '2026-10-02': {'1. open': '360.0800', '2. high': '374.6000', '3. low': '359.4110', '4. close': '370.5900', '5. volume': '55330140'}, '2026-10-01': {'1. open': '356.8100', '2. high': '359.7900', '3. low': '353.8000', '4. close': '354.1100', '5. volume': '31080774'}, '2026-09-30': {'1. open': '352.1100', '2. high': '355.2190', '3. low': '345.8800', '4. close': '354.8100', '5. volume': '39235838'}, '2026-09-29': {'1. open': '358.4000', '2. high': '358.7400', '3. low': '351.6700', '4. close': '352.8400', '5. volume': '32492406'}, '2026-09-28': {'1. open': '368.0600', '2. high': '369.4300', '3. low': '356.8000', '4. close': '357.4500', '5. volume': '39452901'}, '2026-09-25': {'1. open': '384.6200', '2. high': '386.8300', '3. low': '367.6700', '4. close': '372.1100', '5. volume': '45999470'}, '2026-09-24': {'1. open': '377.3500', '2. high': '383.3324', '3. low': '375.7000', '4. close': '377.9400', '5. volume': '26165727'}, '2026-09-23': {'1. open': '380.1000', '2. high': '386.7000', '3. low': '377.5750', '4. close': '380.1200', '5. volume': '33522492'}, '2026-09-22': {'1. open': '379.0690', '2. high': '380.4200', '3. low': '372.8800', '4. close': '378.9000', '5. volume': '28229908'}, '2026-09-21': {'1. open': '371.6350', '2. high': '378.3600', '3. low': '371.0700', '4. close': '375.3000', '5. volume': '36599609'}, '2026-09-18': {'1. open': '369.0000', '2. high': '370.9000', '3. low': '360.7510', '4. close': '364.2700', '5. volume': '51922256'}, '2026-09-17': {'1. open': '367.4800', '2. high': '374.1200', '3. low': '363.2200', '4. close': '366.2000', '5. volume': '38924057'}, '2026-09-16': {'1. open': '357.9250', '2. high': '365.1000', '3. low': '354.8913', '4. close': '358.0800', '5. volume': '32177388'}, '2026-09-15': {'1. open': '358.7500', '2. high': '362.3900', '3. low': '354.0500', '4. close': '356.5800', '5. volume': '30317727'}, '2026-09-14': {'1. open': '359.7800', '2. high': '367.7300', '3. low': '357.0400', '4. close': '358.9700', '5. volume': '32477181'}, '2026-09-11': {'1. open': '364.2000', '2. high': '368.6600', '3. low': '361.6000', '4. close': '365.4400', '5. volume': '30153019'}, '2026-09-10': {'1. open': '360.5950', '2. high': '369.2100', '3. low': '357.6800', '4. close': '363.5600', '5. volume': '29667241'}, '2026-09-09': {'1. open': '368.2500', '2. high': '375.4400', '3. low': '366.0000', '4. close': '367.8100', '5. volume': '32564336'}, '2026-09-08': {'1. open': '357.0950', '2. high': '370.0000', '3. low': '355.7500', '4. close': '368.1600', '5. volume': '51078786'}, '2026-09-04': {'1. open': '362.0700', '2. high': '364.6900', '3. low': '351.3201', '4. close': '354.0800', '5. volume': '65018209'}, '2026-09-03': {'1. open': '365.8200', '2. high': '384.0400', '3. low': '365.8200', '4. close': '376.3650', '5. volume': '63600987'}, '2026-09-02': {'1. open': '360.4100', '2. high': '360.6200', '3. low': '349.9200', '4. close': '357.0100', '5. volume': '33951909'}, '2026-09-01': {'1. open': '360.9000', '2. high': '362.7000', '3. low': '352.9600', '4. close': '356.0900', '5. volume': '36193926'}, '2026-08-31': {'1. open': '347.2100', '2. high': '368.9200', '3. low': '347.1500', '4. close': '367.9500', '5. volume': '61732258'}, '2026-08-28': {'1. open': '357.0950', '2. high': '358.8000', '3. low': '345.2000', '4. close': '348.7500', '5. volume': '32972214'}, '2026-08-27': {'1. open': '346.1550', '2. high': '355.7400', '3. low': '345.4500', '4. close': '354.8100', '5. volume': '30136164'}, '2026-08-26': {'1. open': '345.2700', '2. high': '351.9300', '3. low': '342.5300', '4. close': '345.8200', '5. volume': '28573007'}, '2026-08-25': {'1. open': '349.5800', '2. high': '357.0000', '3. low': '349.2003', '4. close': '350.2500', '5. volume': '29816685'}, '2026-08-24': {'1. open': '361.4100', '2. high': '363.2400', '3. low': '348.2600', '4. close': '348.9500', '5. volume': '39190484'}, '2026-08-21': {'1. open': '349.8800', '2. high': '366.5000', '3. low': '346.9000', '4. close': '362.8600', '5. volume': '59223958'}, '2026-08-20': {'1. open': '346.2000', '2. high': '347.5000', '3. low': '338.9600', '4. close': '345.1300', '5. volume': '30766360'}, '2026-08-19': {'1. open': '338.8900', '2. high': '351.6200', '3. low': '335.7000', '4. close': '351.1200', '5. volume': '36735428'}, '2026-08-18': {'1. open': '333.2200', '2. high': '340.5300', '3. low': '331.1200', '4. close': '336.8700', '5. volume': '27994466'}, '2026-08-17': {'1. open': '340.6900', '2. high': '345.4500', '3. low': '337.4800', '4. close': '339.3000', '5. volume': '26037093'}, '2026-08-14': {'1. open': '342.3300', '2. high': '351.2600', '3. low': '335.3306', '4. close': '342.2700', '5. volume': '45437144'}, '2026-08-13': {'1. open': '327.2000', '2. high': '341.6400', '3. low': '325.2400', '4. close': '339.9600', '5. volume': '34708303'}, '2026-08-12': {'1. open': '335.0000', '2. high': '335.5000', '3. low': '323.6400', '4. close': '327.5100', '5. volume': '28698879'}, '2026-08-11': {'1. open': '332.8000', '2. high': '336.2000', '3. low': '329.5300', '4. close': '332.8100', '5. volume': '23345233'}, '2026-08-10': {'1. open': '326.5950', '2. high': '332.0500', '3. low': '326.1500', '4. close': '330.8800', '5. volume': '25003808'}, '2026-08-07': {'1. open': '322.3400', '2. high': '333.7300', '3. low': '321.2508', '4. close': '328.5800', '5. volume': '39492345'}, '2026-08-06': {'1. open': '317.0500', '2. high': '323.0000', '3. low': '315.5205', '4. close': '319.5300', '5. volume': '26033776'}, '2026-08-05': {'1. open': '323.4200', '2. high': '327.1400', '3. low': '320.2800', '4. close': '321.5500', '5. volume': '27820813'}, '2026-08-04': {'1. open': '324.0000', '2. high': '329.5700', '3. low': '320.7901', '4. close': '327.3500', '5. volume': '33318303'}, '2026-08-03': {'1. open': '310.9600', '2. high': '324.6500', '3. low': '310.4250', '4. close': '322.0800', '5. volume': '38281362'}, '2026-07-31': {'1. open': '309.6900', '2. high': '315.5000', '3. low': '301.9700', '4. close': '311.2100', '5. volume': '36630560'}, '2026-07-30': {'1. open': '302.7000', '2. high': '310.8700', '3. low': '301.3300', '4. close': '308.8500', '5. volume': '38005390'}, '2026-07-29': {'1. open': '307.1400', '2. high': '309.0600', '3. low': '297.3800', '4. close': '298.3200', '5. volume': '39478039'}, '2026-07-28': {'1. open': '305.9250', '2. high': '311.1600', '3. low': '300.6900', '4. close': '307.4400', '5. volume': '39802421'}, '2026-07-27': {'1. open': '313.2400', '2. high': '317.0000', '3. low': '304.2800', '4. close': '309.2200', '5. volume': '44919377'}, '2026-07-24': {'1. open': '320.7200', '2. high': '322.9600', '3. low': '306.5100', '4. close': '313.0300', '5. volume': '62760007'}, '2026-07-23': {'1. open': '341.0000', '2. high': '342.1100', '3. low': '315.7350', '4. close': '319.6900', '5. volume': '115606413'}, '2026-07-22': {'1. open': '375.5300', '2. high': '380.1700', '3. low': '372.9000', '4. close': '374.0100', '5. volume': '30646124'}, '2026-07-21': {'1. open': '371.1650', '2. high': '384.0700', '3. low': '369.9800', '4. close': '378.9300', '5. volume': '32735334'}, '2026-07-20': {'1. open': '386.0450', '2. high': '386.6100', '3. low': '369.4250', '4. close': '369.5700', '5. volume': '33901516'}, '2026-07-17': {'1. open': '381.7800', '2. high': '385.6899', '3. low': '377.2200', '4. close': '380.8400', '5. volume': '31394594'}, '2026-07-16': {'1. open': '392.3500', '2. high': '395.3100', '3. low': '385.3200', '4. close': '391.0600', '5. volume': '29269113'}, '2026-07-15': {'1. open': '399.3950', '2. high': '406.5895', '3. low': '390.6600', '4. close': '394.4600', '5. volume': '31549805'}, '2026-07-14': {'1. open': '399.0500', '2. high': '402.2200', '3. low': '394.7600', '4. close': '396.1800', '5. volume': '23384992'}, '2026-07-13': {'1. open': '404.6100', '2. high': '405.5700', '3. low': '391.3700', '4. close': '394.7600', '5. volume': '32809171'}, '2026-07-10': {'1. open': '410.4900', '2. high': '413.1600', '3. low': '402.8101', '4. close': '407.7600', '5. volume': '33409995'}, '2026-07-09': {'1. open': '393.9900', '2. high': '407.8600', '3. low': '390.8631', '4. close': '406.5500', '5. volume': '37834988'}, '2026-07-08': {'1. open': '399.3750', '2. high': '399.6300', '3. low': '390.5100', '4. close': '394.0600', '5. volume': '33844906'}, '2026-07-07': {'1. open': '416.9600', '2. high': '419.5600', '3. low': '401.8800', '4. close': '402.9000', '5. volume': '38149901'}, '2026-07-06': {'1. open': '397.5000', '2. high': '420.0000', '3. low': '390.5000', '4. close': '419.7700', '5. volume': '54727861'}, '2026-07-02': {'1. open': '428.0100', '2. high': '432.3500', '3. low': '389.3011', '4. close': '393.4500', '5. volume': '73915762'}, '2026-07-01': {'1. open': '421.4600', '2. high': '432.8599', '3. low': '418.0901', '4. close': '425.3000', '5. volume': '40127902'}, '2026-06-30': {'1. open': '406.0000', '2. high': '424.5400', '3. low': '406.0000', '4. close': '420.6000', '5. volume': '43385619'}, '2026-06-29': {'1. open': '381.7900', '2. high': '413.2700', '3. low': '379.3000', '4. close': '411.8400', '5. volume': '57645798'}, '2026-06-26': {'1. open': '370.1500', '2. high': '387.8000', '3. low': '368.6000', '4. close': '379.7100', '5. volume': '53434138'}, '2026-06-25': {'1. open': '375.2700', '2. high': '379.1170', '3. low': '371.2210', '4. close': '375.1200', '5. volume': '30259987'}, '2026-06-24': {'1. open': '380.0800', '2. high': '384.5800', '3. low': '373.0500', '4. close': '375.5300', '5. volume': '37081421'}, '2026-06-23': {'1. open': '392.6100', '2. high': '392.8700', '3. low': '379.0600', '4. close': '381.6100', '5. volume': '50420210'}, '2026-06-22': {'1. open': '394.8500', '2. high': '414.7500', '3. low': '394.4000', '4. close': '405.0500', '5. volume': '47819486'}, '2026-06-18': {'1. open': '398.0950', '2. high': '402.5200', '3. low': '384.7000', '4. close': '400.4900', '5. volume': '58384713'}, '2026-06-17': {'1. open': '401.5300', '2. high': '405.9400', '3. low': '393.7600', '4. close': '396.3800', '5. volume': '43534299'}, '2026-06-16': {'1. open': '404.1100', '2. high': '412.4200', '3. low': '400.5400', '4. close': '404.6600', '5. volume': '40255473'}, '2026-06-15': {'1. open': '412.3700', '2. high': '416.0000', '3. low': '407.1000', '4. close': '411.1500', '5. volume': '45620514'}, '2026-06-12': {'1. open': '399.4900', '2. high': '406.6800', '3. low': '386.7600', '4. close': '406.4300', '5. volume': '63652286'}, '2026-06-11': {'1. open': '388.2800', '2. high': '399.5400', '3. low': '380.6600', '4. close': '399.1500', '5. volume': '45324348'}, '2026-06-10': {'1. open': '391.5400', '2. high': '397.0900', '3. low': '380.1500', '4. close': '381.5900', '5. volume': '49695583'}, '2026-06-09': {'1. open': '411.0300', '2. high': '418.5000', '3. low': '384.2400', '4. close': '396.6800', '5. volume': '59940230'}, '2026-06-08': {'1. open': '396.3300', '2. high': '412.9400', '3. low': '394.7200', '4. close': '408.9500', '5. volume': '50328834'}, '2026-06-05': {'1. open': '420.5000', '2. high': '424.6799', '3. low': '388.5900', '4. close': '391.0000', '5. volume': '63420177'}, '2026-06-04': {'1. open': '419.8400', '2. high': '426.3499', '3. low': '417.1600', '4. close': '418.4500', '5. volume': '35323259'}, '2026-06-03': {'1. open': '418.7000', '2. high': '433.6000', '3. low': '416.0000', '4. close': '423.7000', '5. volume': '44500733'}, '2026-06-02': {'1. open': '418.2200', '2. high': '424.4200', '3. low': '413.6500', '4. close': '423.7400', '5. volume': '37596045'}, '2026-06-01': {'1. open': '427.4900', '2. high': '429.6000', '3. low': '415.4300', '4. close': '415.8800', '5. volume': '44937852'}, '2026-05-29': {'1. open': '439.8450', '2. high': '441.0700', '3. low': '428.1400', '4. close': '435.7900', '5. volume': '45176821'}, '2026-05-28': {'1. open': '437.6150', '2. high': '443.9600', '3. low': '436.3000', '4. close': '442.1000', '5. volume': '32434996'}, '2026-05-27': {'1. open': '442.8900', '2. high': '445.6000', '3. low': '435.5200', '4. close': '440.3600', '5. volume': '44656505'}, '2026-05-26': {'1. open': '430.2600', '2. high': '435.2000', '3. low': '426.1200', '4. close': '433.5900', '5. volume': '45658897'}, '2026-05-22': {'1. open': '422.6650', '2. high': '431.5100', '3. low': '420.5100', '4. close': '426.0100', '5. volume': '46104710'}, '2026-05-21': {'1. open': '422.1750', '2. high': '426.9500', '3. low': '412.9000', '4. close': '417.8500', '5. volume': '42636854'}, '2026-05-20': {'1. open': '407.6000', '2. high': '417.4600', '3. low': '406.3900', '4. close': '417.2600', '5. volume': '44484579'}, '2026-05-19': {'1. open': '403.1600', '2. high': '405.6300', '3. low': '393.6300', '4. close': '404.1100', '5. volume': '46500551'}}

[None, None]

In [12]:
#load_dotenv(find_dotenv(usecwd=True), override=True)

In [13]:
news_api_key = os.getenv("NEWS_API_KEY")

In [ ]:
news_url = 'https://newsapi.org/v2/everything?'
 
params2 = {'q': 'tesla', 
       'from': '2026-10-01',
       'sortBy': 'popularity',
       'apiKey': news_api_key,
}

In [21]:
r_news = requests.get(news_url, params=params2)
data = r_news.json()

In [ ]:
[a['content'] for a in data['articles'][:3]]

['<ul><li></li><li></li><li></li></ul>\r\nThe companys sales dipped in the third quarter, after customers raced to cash in on expiring tax credits last year.\r\nThe companys sales dipped in the third quart… [+3609 chars]',
 '<ul><li></li><li></li><li></li></ul>\r\nThe new feature was in response to a mass shooting that took place at a Supercharger station in Idaho.\r\nThe new feature was in response to a mass shooting that t… [+3262 chars]',
 '<ul><li></li><li></li><li></li></ul>\r\nThings went just great for Henry VIIIs wives, too\r\nThings went just great for Henry VIIIs wives, too\r\nby\r\nElizabeth LopattoClose\r\nPosts from this author will be … [+5443 chars]']

In [26]:
import pandas as pd

df = pd.json_normalize(data['articles'])   # flattens source.id / source.name into columns
df[['source.name', 'title', 'publishedAt', 'content']].head(3)

,source.name,title,publishedAt,content
0,The Verge,Tesla’s recovery hits a speed bump,2026-10-02T13:19:59Z,<ul><li></li><li></li><li></li></ul>\r\nThe co...
1,The Verge,Tesla will now let you drive off mid-charge if...,2026-10-02T14:34:14Z,<ul><li></li><li></li><li></li></ul>\r\nThe ne...
2,The Verge,Breaking up (with Elon Musk) is hard to do,2026-10-02T17:37:36Z,<ul><li></li><li></li><li></li></ul>\r\nThings...

In [27]:
import re

def clean(text):
    if not text:
        return text
    text = re.sub(r'<[^>]+>', '', text)        # remove any HTML tags
    return re.sub(r'\s+', ' ', text).strip()    # collapse \r\n and extra spaces

df['content'] = df['content'].apply(clean)

In [28]:
df[['source.name', 'title', 'publishedAt', 'content']].head(3)

,source.name,title,publishedAt,content
0,The Verge,Tesla’s recovery hits a speed bump,2026-10-02T13:19:59Z,The companys sales dipped in the third quarter...
1,The Verge,Tesla will now let you drive off mid-charge if...,2026-10-02T14:34:14Z,The new feature was in response to a mass shoo...
2,The Verge,Breaking up (with Elon Musk) is hard to do,2026-10-02T17:37:36Z,"Things went just great for Henry VIIIs wives, ..."